/*
Copyright (C) 1996-1997 Id Software, Inc.
Copyright (C) 2026 MiniQuake contributors

BP-010 byte-exact Protocol 15, MSG_* and SZ_* fixtures. Golden byte streams
were generated by tools/oracle/protocol15_common_oracle.c from the WinQuake
1.09 release semantics and are checked independently by
 tools/check_protocol15_vectors.py.
*/

import miniquake.types as t
import miniquake.constants as c
import miniquake.byteio as bio
import miniquake.sizebuf as sz
import miniquake.message as msg
import miniquake.protocol_text as protocolText
import miniquake.protocol_write as protocolWrite

function assertEqual(actual, expected, name)
  if actual != expected then return error(9300, name + ": expected " + expected + ", got " + actual) end if
  return true
end function

function assertTrue(value, name)
  if value != true then return error(9301, name + ": expected true") end if
  return true
end function

function assertHex(data, expected, name)
  return assertEqual(hex(data), expected, name)
end function

function runTest(number, name, fn)
  print "  [" + number + "/15] " + name
  result = try(fn())
  if result is error then
    print "    FAIL: " + result.message
    return false
  end if
  return true
end function

function testProtocolConstants()
  assertEqual(c.PROTOCOL_VERSION, 15, "PROTOCOL_VERSION")
  assertEqual(c.CLC_MOVE, 3, "clc_move")
  assertEqual(c.CLC_STRINGCMD, 4, "clc_stringcmd")
  assertEqual(c.SVC_SERVERINFO, 11, "svc_serverinfo")
  assertEqual(c.SVC_CLIENTDATA, 15, "svc_clientdata")
  assertEqual(c.SVC_SPAWNBASELINE, 22, "svc_spawnbaseline")
  assertEqual(c.U_SIGNAL, 128, "U_SIGNAL")
  assertEqual(c.U_LONGENTITY, 16384, "U_LONGENTITY")
  assertEqual(c.SU_WEAPON, 16384, "SU_WEAPON")
  return true
end function

function testPrimitiveStream()
  buffer = sz.alloc(256)
  msg.writeChar(buffer, -2)
  msg.writeByte(buffer, 254)
  msg.writeShort(buffer, -1234)
  msg.writeLong(buffer, 0x12345678)
  msg.writeFloat(buffer, 12.5)
  msg.writeString(buffer, "quake")
  msg.writeCoord(buffer, -12.25)
  msg.writeAngle(buffer, 90.75)
  assertHex(sz.dataSlice(buffer), "fefe2efb78563412000048417175616b65009eff40", "primitive_stream")
  return true
end function

function testReleaseWrapping()
  buffer = sz.alloc(64)
  msg.writeChar(buffer, 130)
  msg.writeByte(buffer, -1)
  msg.writeShort(buffer, 0x12345)
  msg.writeLong(buffer, -2)
  assertHex(sz.dataSlice(buffer), "82ff4523feffffff", "release_wrapping")
  reader = msg.beginReading(buffer)
  assertEqual(msg.readChar(reader), -126, "wrapped MSG_ReadChar")
  assertEqual(msg.readByte(reader), 255, "wrapped MSG_ReadByte")
  assertEqual(msg.readShort(reader), 0x2345, "wrapped MSG_ReadShort")
  assertEqual(msg.readLong(reader), -2, "negative MSG_ReadLong")

  booleanBuffer = sz.alloc(2)
  msg.writeByte(booleanBuffer, false)
  msg.writeByte(booleanBuffer, true)
  assertHex(sz.dataSlice(booleanBuffer), "0001", "qboolean integer ABI")
  return true
end function

function testCoordAngleBoundaries()
  buffer = sz.alloc(128)
  msg.writeCoord(buffer, -0.124)
  msg.writeCoord(buffer, -0.126)
  msg.writeCoord(buffer, 4095.875)
  msg.writeCoord(buffer, 4096.0)
  msg.writeAngle(buffer, -1.9)
  msg.writeAngle(buffer, -90.9)
  msg.writeAngle(buffer, 359.9)
  msg.writeAngle(buffer, 360.0)
  assertHex(sz.dataSlice(buffer), "0000ffffff7f008000c0ff00", "coord_angle_boundaries")

  coordReader = msg.beginReadingBytes(fromHex("0080ff7f"))
  assertEqual(msg.readCoord(coordReader), -4096.0, "signed minimum coord")
  assertEqual(msg.readCoord(coordReader), 4095.875, "signed maximum coord")

  angleReader = msg.beginReadingBytes(bytes([0xff, 0xc0, 0x7f, 0]))
  assertEqual(msg.readAngle(angleReader), -1.40625, "signed 0xff angle")
  assertEqual(msg.readAngle(angleReader), -90.0, "signed 0xc0 angle")
  assertEqual(msg.readAngle(angleReader), 178.59375, "signed 0x7f angle")
  assertEqual(msg.readAngle(angleReader), 0.0, "zero angle")
  return true
end function

function testFloatParameterRounding()
  buffer = sz.alloc(64)
  msg.writeFloat(buffer, 16777217)
  msg.writeCoord(buffer, 0.124999999)
  msg.writeCoord(buffer, -0.124999999)
  msg.writeCoord(buffer, 1.99999999)
  msg.writeCoord(buffer, -1.99999999)
  msg.writeAngle(buffer, 1.99999999)
  msg.writeAngle(buffer, -1.99999999)
  // An integral MiniLang caller still crosses the C float parameter boundary.
  msg.writeCoord(buffer, 16777217)
  assertHex(sz.dataSlice(buffer), "0000804b0100ffff1000f0ff01ff0000", "float_parameter_rounding")
  return true
end function

function testHighBitCString()
  raw = bytes([0x41, 0x80, 0xe9, 0xfe])
  text = protocolText.decodeBytes(raw)
  assertHex(protocolText.encodeBytes(text), "4180e9fe", "high-bit text adapter")

  buffer = sz.alloc(64)
  msg.writeString(buffer, text)
  assertHex(sz.dataSlice(buffer), "4180e9fe00", "raw_high_bit_string")

  reader = msg.beginReading(buffer)
  decoded = msg.readString(reader)
  assertHex(protocolText.encodeBytes(decoded), "4180e9fe", "high-bit wire roundtrip")
  assertEqual(reader.readCount, 5, "high-bit read count")
  return true
end function

function testCStringTerminationAndValidation()
  embedded = decode(bytes([0x41, 0x00, 0x42]))
  buffer = sz.alloc(32)
  msg.writeString(buffer, embedded)
  assertHex(sz.dataSlice(buffer), "4100", "embedded_nul_string")

  nullBuffer = sz.alloc(8)
  msg.writeString(nullBuffer, void)
  assertHex(sz.dataSlice(nullBuffer), "00", "null_string")

  stringOverflow = sz.allocOverflowing(5)
  sz.writeBytes(stringOverflow, bytes([9, 9, 9]))
  msg.writeString(stringOverflow, "xy")
  assertHex(sz.dataSlice(stringOverflow), "787900", "string_overflow_restart")
  assertEqual(stringOverflow.overflowed, true, "string overflow flag")

  outsideLatin1 = decode(bytes([0xe2, 0x82, 0xac]))
  rejected = try(protocolText.encodeBytes(outsideLatin1))
  assertTrue(rejected is error, "non-Latin-1 text rejected")

  rawBuffer = sz.alloc(16)
  msg.writeStringBytes(rawBuffer, bytes([0x51, 0x80, 0, 0x52]))
  assertHex(sz.dataSlice(rawBuffer), "518000", "raw string writer stops at NUL")
  rawReader = msg.beginReading(rawBuffer)
  raw = msg.readStringBytes(rawReader)
  assertHex(raw, "5180", "raw string reader")
  return true
end function

function testSizeBufferPrintAndOverflow()
  // Seed a valid empty C string before exercising the original trailing-NUL
  // replacement path. common.c itself is undefined when cursize == 0.
  printable = sz.alloc(64)
  sz.writeBytes(printable, bytes([0]))
  sz.printText(printable, "one")
  sz.printText(printable, "two")
  assertHex(sz.dataSlice(printable), "6f6e6574776f00", "sz_print_concat")

  safeEmpty = sz.alloc(16)
  sz.printText(safeEmpty, "one")
  assertHex(sz.dataSlice(safeEmpty), "6f6e6500", "safe empty SZ_Print divergence")

  high = protocolText.decodeBytes(bytes([0x80, 0xe9]))
  highPrint = sz.alloc(16)
  sz.printText(highPrint, high)
  assertHex(sz.dataSlice(highPrint), "80e900", "SZ_Print high-bit bytes")

  printOverflow = sz.allocOverflowing(5)
  sz.writeBytes(printOverflow, bytes([7, 7, 7]))
  sz.printText(printOverflow, "ab")
  assertHex(sz.dataSlice(printOverflow), "616200", "sz_print_overflow_restart")
  assertEqual(printOverflow.overflowed, true, "SZ_Print overflow flag")

  safeTrailingOverflow = sz.allocOverflowing(4)
  sz.printText(safeTrailingOverflow, "x")
  sz.printText(safeTrailingOverflow, "abc")
  assertHex(sz.dataSlice(safeTrailingOverflow), "61626300", "safe trailing-NUL overflow restart")
  assertEqual(safeTrailingOverflow.overflowed, true, "safe trailing overflow flag")

  overflowing = sz.allocOverflowing(4)
  sz.writeBytes(overflowing, bytes([1, 2, 3, 4]))
  sz.writeBytes(overflowing, bytes([9, 8]))
  assertHex(sz.dataSlice(overflowing), "0908", "sz_overflow_restart")
  assertEqual(overflowing.curSize, 2, "overflow restart size")
  assertEqual(overflowing.overflowed, true, "overflow flag")
  return true
end function

function testPrimitiveReadsAndBounds()
  data = fromHex("fefe2efb78563412000048417175616b65009eff40")
  reader = msg.beginReadingBytes(data)
  assertEqual(msg.readChar(reader), -2, "MSG_ReadChar")
  assertEqual(msg.readByte(reader), 254, "MSG_ReadByte")
  assertEqual(msg.readShort(reader), -1234, "MSG_ReadShort")
  assertEqual(msg.readLong(reader), 0x12345678, "MSG_ReadLong")
  assertEqual(msg.readFloat(reader), 12.5, "MSG_ReadFloat")
  assertEqual(msg.readString(reader), "quake", "MSG_ReadString")
  assertEqual(msg.readCoord(reader), -12.25, "MSG_ReadCoord")
  assertEqual(msg.readAngle(reader), 90.0, "MSG_ReadAngle quantized")
  assertEqual(msg.remaining(reader), 0, "primitive reader exhausted")

  shortReader = msg.beginReadingBytes(bytes([1]))
  assertEqual(msg.readShort(shortReader), -1, "short overflow sentinel")
  assertEqual(shortReader.badRead, true, "short badRead")
  assertEqual(shortReader.readCount, 0, "short overflow does not advance")

  floatReader = msg.beginReadingBytes(bytes([1, 2, 3]))
  assertEqual(msg.readFloat(floatReader), -1.0, "safe float overflow sentinel")
  assertEqual(floatReader.badRead, true, "safe float badRead")
  assertEqual(floatReader.readCount, 0, "safe float overflow does not advance")
  return true
end function

function testReadStringSignedFF()
  reader = msg.beginReadingBytes(bytes([0x41, 0xff, 0x42, 0]))
  assertEqual(msg.readString(reader), "A", "signed 0xff string terminator")
  assertEqual(reader.readCount, 2, "0xff terminator consumed")
  assertEqual(reader.badRead, false, "0xff is not an overread")
  assertEqual(msg.remaining(reader), 2, "0xff leaves suffix unread")
  return true
end function

function testReadStringStaticLimit()
  data = bytes(2050)
  index = 0
  while index < 2049
    data[index] = 0x61
    index = index + 1
  end while
  reader = msg.beginReadingBytes(data)
  result = msg.readString(reader)
  assertEqual(len(protocolText.encodeBytes(result)), 2047, "MSG_ReadString static payload limit")
  assertEqual(reader.readCount, 2047, "static limit read count")
  assertEqual(msg.remaining(reader), 3, "static limit leaves suffix")
  assertEqual(reader.badRead, false, "static limit is not badRead")
  return true
end function

function testClcMoveGolden()
  command = t.UserCommand(
    t.Vec3(12.75, 180.0, -90.9),
    200.75,
    -123.9,
    32768.9,
    3,
    7,
    0,
  )
  buffer = sz.alloc(128)
  protocolWrite.writeMove(buffer, command, 12.5)
  assertHex(sz.dataSlice(buffer), "03000048410880c0c80085ff00800307", "clc_move")
  return true
end function

function testBaselineGolden()
  baseline = [
    1,
    2,
    3,
    4,
    t.Vec3(-12.25, 0.125, 4095.875),
    t.Vec3(90.75, -90.9, 359.9),
  ]
  buffer = sz.alloc(128)
  protocolWrite.writeBaseline(buffer, baseline)
  assertHex(sz.dataSlice(buffer), "010203049eff400100c0ff7fff", "baseline_payload")
  return true
end function

function testAllByteTextAdapter()
  raw = bytes(255)
  index = 0
  while index < 255
    raw[index] = index + 1
    index = index + 1
  end while
  text = protocolText.decodeBytes(raw)
  assertHex(protocolText.encodeBytes(text), hex(raw), "all non-NUL Quake bytes reversible")
  assertEqual(protocolText.TEXT_ABI, "quake_latin1_cstring_v1", "protocol text ABI")
  return true
end function

function testSizeBufferExactFitAndErrors()
  exact = sz.alloc(4)
  offset = sz.getSpace(exact, 4)
  assertEqual(offset, 0, "exact fit offset")
  assertEqual(exact.curSize, 4, "exact fit size")
  failure = try(sz.getSpace(exact, 1))
  assertTrue(failure is error, "overflow without permission rejected")
  assertEqual(exact.curSize, 4, "rejected overflow leaves size")

  tooLarge = sz.allocOverflowing(4)
  failure = try(sz.getSpace(tooLarge, 5))
  assertTrue(failure is error, "single request larger than buffer rejected")
  assertEqual(tooLarge.curSize, 0, "oversized request leaves size")
  assertEqual(tooLarge.overflowed, false, "oversized request leaves overflow flag")
  return true
end function


function main(args)
  print "MiniQuake BP-010R1 Protocol 15 wire tests"
  passed = 0
  if runTest("01", "Protocol 15 constants", testProtocolConstants) then passed = passed + 1 end if
  if runTest("02", "primitive MSG stream", testPrimitiveStream) then passed = passed + 1 end if
  if runTest("03", "release integer wrapping", testReleaseWrapping) then passed = passed + 1 end if
  if runTest("04", "coord and angle boundaries", testCoordAngleBoundaries) then passed = passed + 1 end if
  if runTest("05", "C float-parameter rounding", testFloatParameterRounding) then passed = passed + 1 end if
  if runTest("06", "high-bit Quake C strings", testHighBitCString) then passed = passed + 1 end if
  if runTest("07", "C-string termination and validation", testCStringTerminationAndValidation) then passed = passed + 1 end if
  if runTest("08", "SZ_Print and overflow restart", testSizeBufferPrintAndOverflow) then passed = passed + 1 end if
  if runTest("09", "primitive reads and bounds", testPrimitiveReadsAndBounds) then passed = passed + 1 end if
  if runTest("10", "signed 0xff string termination", testReadStringSignedFF) then passed = passed + 1 end if
  if runTest("11", "MSG_ReadString static limit", testReadStringStaticLimit) then passed = passed + 1 end if
  if runTest("12", "CL_SendMove wire image", testClcMoveGolden) then passed = passed + 1 end if
  if runTest("13", "baseline wire image", testBaselineGolden) then passed = passed + 1 end if
  if runTest("14", "all non-NUL Quake bytes", testAllByteTextAdapter) then passed = passed + 1 end if
  if runTest("15", "sizebuf exact fit and errors", testSizeBufferExactFitAndErrors) then passed = passed + 1 end if

  if passed != 15 then
    print "MiniQuake BP-010R1 Protocol 15 wire tests failed: " + passed + "/15"
    return 1
  end if
  print "MiniQuake BP-010R1 Protocol 15 wire tests passed: 15"
  return 0
end function
