#!/usr/bin/env python3
# Copyright (c) 1996-1997 Id Software, Inc.
# Copyright (c) 2026 Nils Kopal
# SPDX-License-Identifier: GPL-2.0-or-later

"""Validate MiniQuake BP-010R1 Protocol-15 golden vectors and source contract.

The checked-in vectors are generated by a standalone C oracle reproducing the
WinQuake 1.09 common.c MSG_*/SZ_* release semantics. This checker always
recomputes them with an independent Python model. When a C compiler is
available it also builds and runs the oracle; --require-c-oracle makes that
step mandatory (used for release packaging, not for the Windows user test).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass, field
from pathlib import Path

PACKAGE_ID = "BP-010R1"
SCHEMA = "MiniQuakeProtocol15Golden/1"
TEXT_ABI = "quake_latin1_cstring_v1"


@dataclass
class Check:
    """Represent one check discovered by the source verifier."""
    name: str
    passed: bool
    details: dict[str, object] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class Report:
    """Collect the machine-readable outcome of one verification run."""
    package_id: str
    root: str
    passed: bool
    checks: list[Check]


def sha256(path: Path) -> str:
    """Compute the SHA-256 digest of the requested file."""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


class Buffer:
    """Encode deterministic protocol bytes for the reference vectors."""
    def __init__(self, maximum: int, allow_overflow: bool = False) -> None:
        """Initialize the helper with its immutable verification inputs."""
        self.data = bytearray(maximum)
        self.maximum = maximum
        self.size = 0
        self.allow_overflow = allow_overflow
        self.overflowed = False

    def space(self, count: int) -> int:
        """Compute the reference space value for a deterministic fixture."""
        if self.size + count > self.maximum:
            if not self.allow_overflow or count > self.maximum:
                raise OverflowError(count)
            self.overflowed = True
            self.size = 0
        offset = self.size
        self.size += count
        return offset

    def write(self, payload: bytes) -> None:
        """Append payload bytes to the bounded fixture buffer."""
        offset = self.space(len(payload))
        self.data[offset : offset + len(payload)] = payload

    def result(self) -> bytes:
        """Return the bytes currently written to the bounded fixture buffer."""
        return bytes(self.data[: self.size])


def i32(value: int) -> int:
    """Interpret the low 32 bits as a signed integer."""
    value &= 0xFFFFFFFF
    return value - 0x100000000 if value >= 0x80000000 else value


def trunc_zero(value: float) -> int:
    """Compute the reference trunc zero value for a deterministic fixture."""
    return int(value)


def write_char(b: Buffer, value: int) -> None:
    """Encode and write char to the fixture buffer."""
    b.write(bytes([value & 0xFF]))


def write_byte(b: Buffer, value: int) -> None:
    """Encode and write byte to the fixture buffer."""
    b.write(bytes([value & 0xFF]))


def write_short(b: Buffer, value: int) -> None:
    """Encode and write short to the fixture buffer."""
    value &= 0xFFFF
    b.write(bytes((value & 0xFF, (value >> 8) & 0xFF)))


def write_long(b: Buffer, value: int) -> None:
    """Encode and write long to the fixture buffer."""
    b.write(struct.pack("<I", value & 0xFFFFFFFF))


def f32(value: float) -> float:
    """Round a value through the IEEE-754 binary32 representation."""
    return struct.unpack("<f", struct.pack("<f", value))[0]


def write_float(b: Buffer, value: float) -> None:
    """Encode and write float to the fixture buffer."""
    b.write(struct.pack("<f", f32(value)))


def write_string(b: Buffer, payload: bytes | None) -> None:
    """Encode and write string to the fixture buffer."""
    if payload is None:
        b.write(b"\0")
        return
    payload = payload.split(b"\0", 1)[0]
    b.write(payload + b"\0")


def write_coord(b: Buffer, value: float) -> None:
    """Encode and write coord to the fixture buffer."""
    product = f32(f32(value) * f32(8.0))
    write_short(b, trunc_zero(product))


def c_div(a: int, b: int) -> int:
    """Reproduce the reference c div operation for differential testing."""
    return int(a / b)


def write_angle(b: Buffer, value: float) -> None:
    """Encode and write angle to the fixture buffer."""
    write_byte(b, c_div(trunc_zero(f32(value)) * 256, 360) & 255)


def sz_print(b: Buffer, payload: bytes) -> None:
    """Append a NUL-terminated string using Quake's SZ_Print overwrite rule."""
    payload = payload.split(b"\0", 1)[0] + b"\0"
    if b.size == 0:
        raise ValueError("original SZ_Print is undefined for cursize == 0")
    if b.data[b.size - 1] != 0:
        b.write(payload)
    else:
        offset = b.space(len(payload) - 1)
        start = offset - 1
        b.data[start : start + len(payload)] = payload


def vector(name: str, b: Buffer) -> dict[str, object]:
    """Package one encoded protocol message as a deterministic vector row."""
    item: dict[str, object] = {"name": name, "bytes": b.result().hex(), "length": b.size}
    if b.overflowed:
        item["overflowed"] = True
    return item


def python_vectors() -> list[dict[str, object]]:
    """Build the deterministic python vectors consumed by this verifier."""
    out: list[dict[str, object]] = []

    b = Buffer(256)
    write_char(b, -2); write_byte(b, 254); write_short(b, -1234)
    write_long(b, 0x12345678); write_float(b, 12.5); write_string(b, b"quake")
    write_coord(b, -12.25); write_angle(b, 90.75)
    out.append(vector("primitive_stream", b))

    b = Buffer(64)
    write_char(b, 130); write_byte(b, -1); write_short(b, 0x12345); write_long(b, -2)
    out.append(vector("release_wrapping", b))

    b = Buffer(128)
    for value in (-0.124, -0.126, 4095.875, 4096.0): write_coord(b, value)
    for value in (-1.9, -90.9, 359.9, 360.0): write_angle(b, value)
    out.append(vector("coord_angle_boundaries", b))

    b = Buffer(128)
    write_float(b, f32(16777217))
    for value in (0.124999999, -0.124999999, 1.99999999, -1.99999999):
        write_coord(b, value)
    for value in (1.99999999, -1.99999999):
        write_angle(b, value)
    write_coord(b, f32(16777217))
    out.append(vector("float_parameter_rounding", b))

    b = Buffer(64); write_string(b, bytes((0x41, 0x80, 0xE9, 0xFE)))
    out.append(vector("raw_high_bit_string", b))

    b = Buffer(64); write_string(b, b"A\0B")
    out.append(vector("embedded_nul_string", b))

    b = Buffer(64); write_string(b, None)
    out.append(vector("null_string", b))

    b = Buffer(5, True); b.write(bytes((9, 9, 9))); write_string(b, b"xy")
    out.append(vector("string_overflow_restart", b))

    b = Buffer(64); b.write(b"\0"); sz_print(b, b"one"); sz_print(b, b"two")
    out.append(vector("sz_print_concat", b))

    b = Buffer(5, True); b.write(bytes((7, 7, 7))); sz_print(b, b"ab")
    out.append(vector("sz_print_overflow_restart", b))

    b = Buffer(4, True); b.write(bytes((1, 2, 3, 4))); b.write(bytes((9, 8)))
    out.append(vector("sz_overflow_restart", b))

    b = Buffer(128)
    write_byte(b, 3); write_float(b, 12.5)
    for value in (12.75, 180.0, -90.9): write_angle(b, value)
    for value in (200.75, -123.9, 32768.9): write_short(b, trunc_zero(f32(value)))
    write_byte(b, 3); write_byte(b, 7)
    out.append(vector("clc_move", b))

    b = Buffer(128)
    for value in (1, 2, 3, 4): write_byte(b, value)
    origins = (-12.25, 0.125, 4095.875)
    angles = (90.75, -90.9, 359.9)
    for origin, angle in zip(origins, angles):
        write_coord(b, origin); write_angle(b, angle)
    out.append(vector("baseline_payload", b))
    return out


def check_document(root: Path) -> Check:
    """Validate document and return its contract findings."""
    path = root / "audit/protocol15_wire_golden.json"
    errors: list[str] = []
    details: dict[str, object] = {}
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
        details["schema"] = doc.get("schema")
        details["vector_count"] = len(doc.get("vectors", []))
        details["protocol_version"] = doc.get("protocol_version")
        if doc.get("schema") != SCHEMA: errors.append("unexpected golden schema")
        if doc.get("package") != PACKAGE_ID: errors.append("golden package marker mismatch")
        if doc.get("string_abi") != TEXT_ABI: errors.append("golden string ABI mismatch")
        if doc.get("protocol_version") != 15: errors.append("golden protocol version is not 15")
        expected = python_vectors()
        if doc.get("vectors") != expected:
            errors.append("checked-in vectors differ from the independent Python model")
        oracle_rel = doc.get("reference", {}).get("oracle_source")
        oracle_hash = doc.get("reference", {}).get("oracle_sha256")
        oracle = root / str(oracle_rel)
        if not oracle.is_file():
            errors.append(f"oracle source is missing: {oracle_rel}")
        elif sha256(oracle) != oracle_hash:
            errors.append("oracle source SHA-256 differs from golden metadata")
        details["golden_sha256"] = sha256(path)
        details["oracle_sha256"] = sha256(oracle) if oracle.is_file() else ""
    except (OSError, json.JSONDecodeError, TypeError) as exc:
        errors.append(f"cannot validate golden document: {exc}")
    return Check("golden_vectors", not errors, details, errors)


def parse_oracle_output(text: str) -> list[dict[str, object]]:
    """Parse oracle output into its normalized representation."""
    result: list[dict[str, object]] = []
    for number, line in enumerate(text.splitlines(), 1):
        if not line.strip():
            continue
        value = json.loads(line)
        if not isinstance(value, dict):
            raise ValueError(f"oracle line {number} is not an object")
        result.append(value)
    return result


def compiler_candidates() -> list[list[str]]:
    """Return candidate C compiler commands in preference order."""
    env = os.environ.get("CC", "").strip()
    result: list[list[str]] = []
    if env:
        result.append(env.split())
    for name in ("cc", "gcc", "clang", "cl"):
        path = shutil.which(name)
        if path:
            result.append([path])
    unique: list[list[str]] = []
    seen: set[tuple[str, ...]] = set()
    for item in result:
        key = tuple(item)
        if key not in seen:
            seen.add(key); unique.append(item)
    return unique


def check_c_oracle(root: Path, required: bool) -> Check:
    """Validate c oracle and return its contract findings."""
    source = root / "tools/oracle/protocol15_common_oracle.c"
    errors: list[str] = []
    warnings: list[str] = []
    details: dict[str, object] = {"required": required, "compiled": False}
    candidates = compiler_candidates()
    if not candidates:
        message = "no C compiler found; independent Python model still validated the vectors"
        if required: errors.append(message)
        else: warnings.append(message)
        return Check("c_oracle", not errors, details, errors, warnings)

    last_output = ""
    for command in candidates:
        with tempfile.TemporaryDirectory(prefix="mq-protocol15-") as temporary:
            exe = Path(temporary) / ("oracle.exe" if os.name == "nt" else "oracle")
            if Path(command[0]).name.lower() in {"cl", "cl.exe"}:
                object_file = Path(temporary) / "protocol15_common_oracle.obj"
                compile_command = command + [
                    "/nologo", "/W4", "/WX", "/O2", str(source),
                    f"/Fo:{object_file}", f"/Fe:{exe}",
                ]
            else:
                compile_command = command + ["-std=c11", "-Wall", "-Wextra", "-Werror", "-O2", str(source), "-o", str(exe)]
            completed = subprocess.run(
                compile_command,
                cwd=temporary,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                check=False,
            )
            last_output = completed.stdout.strip()
            if completed.returncode != 0 or not exe.is_file():
                continue
            run = subprocess.run([str(exe)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, check=False)
            last_output = run.stdout.strip()
            if run.returncode != 0:
                continue
            try:
                observed = parse_oracle_output(run.stdout)
            except (json.JSONDecodeError, ValueError) as exc:
                last_output = str(exc)
                continue
            expected = python_vectors()
            if observed != expected:
                errors.append("compiled C oracle output differs from the Python model")
            details.update({"compiled": True, "compiler": command[0], "vector_count": len(observed)})
            return Check("c_oracle", not errors, details, errors, warnings)
    message = "all discovered C compilers failed to build or run the oracle: " + last_output
    if required:
        errors.append(message)
    else:
        warnings.append(message)
    return Check("c_oracle", not errors, details, errors, warnings)


def parse_constants(path: Path) -> dict[str, int]:
    """Parse constants into its normalized representation."""
    values: dict[str, int] = {}
    pattern = re.compile(r"^\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(-?(?:0x[0-9A-Fa-f]+|[0-9]+))\s*$")
    for line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            values[match.group(1)] = int(match.group(2), 0)
    return values


def check_constants(root: Path) -> Check:
    """Validate constants and return its contract findings."""
    expected = {
        "PROTOCOL_VERSION": 15,
        "CLC_BAD": 0, "CLC_NOP": 1, "CLC_DISCONNECT": 2, "CLC_MOVE": 3, "CLC_STRINGCMD": 4,
        "SVC_SERVERINFO": 11, "SVC_CLIENTDATA": 15, "SVC_SPAWNBASELINE": 22,
        "U_MOREBITS": 1, "U_SIGNAL": 128, "U_LONGENTITY": 16384,
        "SU_ITEMS": 512, "SU_ONGROUND": 1024, "SU_INWATER": 2048, "SU_WEAPON": 16384,
        "SND_VOLUME": 1, "SND_ATTENUATION": 2,
    }
    errors: list[str] = []
    values = parse_constants(root / "src/miniquake/constants.ml")
    for name, wanted in expected.items():
        observed = values.get(name)
        if observed != wanted:
            errors.append(f"{name}: expected {wanted}, found {observed}")
    return Check("protocol_constants", not errors, {"constants_checked": len(expected)}, errors)


def check_minilang_contract(root: Path) -> Check:
    """Validate minilang contract and return its contract findings."""
    errors: list[str] = []
    details: dict[str, object] = {}
    protocol_text = (root / "src/miniquake/protocol_text.ml").read_text(encoding="utf-8")
    message = (root / "src/miniquake/message.ml").read_text(encoding="utf-8")
    sizebuf = (root / "src/miniquake/sizebuf.ml").read_text(encoding="utf-8")
    tests = (root / "tests/protocol15_wire_tests.ml").read_text(encoding="utf-8")
    markers = {
        "protocol_text ABI": (protocol_text, f'const TEXT_ABI = "{TEXT_ABI}"'),
        "Latin-1 encoder": (protocol_text, "function encodeBytes(text)"),
        "Latin-1 decoder": (protocol_text, "function decodeBytes(data)"),
        "raw write helper": (message, "function writeStringBytes(buffer, data)"),
        "atomic string reservation": (message, "offset = sz.getSpace(buffer, count + 1)"),
        "raw read helper": (message, "function readStringBytes(reader)"),
        "message encoder": (message, "protocolText.encodeBytes(text)"),
        "message decoder": (message, "protocolText.decodeBytes(readStringBytes(reader))"),
        "sizebuf encoder": (sizebuf, "protocolText.encodeBytes(text)"),
        "atomic SZ_Print reservation": (sizebuf, "offset = getSpace(buffer, count + 1)"),
        "trailing-NUL overflow guard": (sizebuf, "replacesTerminator and buffer.curSize + count > buffer.maxSize"),
        "test count": (tests, "Protocol 15 wire tests passed: 15"),
        "high-bit fixture": (tests, "4180e9fe00"),
        "string overflow fixture": (tests, "string_overflow_restart"),
        "SZ_Print overflow fixture": (tests, "sz_print_overflow_restart"),
        "safe empty SZ_Print fixture": (tests, "safe empty SZ_Print divergence"),
        "move fixture": (tests, "03000048410880c0c80085ff00800307"),
        "baseline fixture": (tests, "010203049eff400100c0ff7fff"),
    }
    for label, (text, marker) in markers.items():
        if marker not in text:
            errors.append(f"missing {label} marker: {marker}")
    vector_doc = json.loads((root / "audit/protocol15_wire_golden.json").read_text(encoding="utf-8"))
    missing_vectors = []
    for item in vector_doc["vectors"]:
        if item["bytes"] not in tests:
            missing_vectors.append(item["name"])
    if missing_vectors:
        errors.append("MiniLang tests do not embed vectors: " + ", ".join(missing_vectors))
    details["vectors_referenced"] = len(vector_doc["vectors"]) - len(missing_vectors)
    details["test_fixtures"] = 15
    return Check("minilang_wire_contract", not errors, details, errors)


def run(root: Path, require_c: bool) -> Report:
    """Run run and capture its deterministic result."""
    checks = [
        check_document(root),
        check_c_oracle(root, require_c),
        check_constants(root),
        check_minilang_contract(root),
    ]
    return Report(PACKAGE_ID, str(root), all(item.passed for item in checks), checks)


def print_report(report: Report) -> None:
    """Emit report in the requested report format."""
    print(f"MiniQuake {report.package_id} Protocol 15 vector verification")
    for item in report.checks:
        print(f"  [{'PASS' if item.passed else 'FAIL'}] {item.name}")
        for warning in item.warnings: print(f"         warning: {warning}")
        for error in item.errors: print(f"         error: {error}")
        if item.details:
            compact = ", ".join(f"{k}={v}" for k, v in item.details.items())
            print(f"         {compact}")
    print(f"MiniQuake {report.package_id} Protocol 15 vector verification: {'PASS' if report.passed else 'FAIL'}")


def self_test() -> int:
    """Exercise the tool with synthetic fixtures and verify its invariants."""
    vectors = python_vectors()
    assert len(vectors) == 13
    by_name = {item["name"]: item for item in vectors}
    assert by_name["primitive_stream"]["bytes"] == "fefe2efb78563412000048417175616b65009eff40"
    assert by_name["float_parameter_rounding"]["bytes"] == "0000804b0100ffff1000f0ff01ff0000"
    assert by_name["string_overflow_restart"]["bytes"] == "787900"
    assert by_name["sz_print_overflow_restart"]["bytes"] == "616200"
    assert by_name["clc_move"]["bytes"] == "03000048410880c0c80085ff00800307"
    assert by_name["baseline_payload"]["bytes"] == "010203049eff400100c0ff7fff"
    print("MiniQuake Protocol 15 vector checker self-test: PASS")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the command-line workflow and return its process exit status."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--json-output")
    parser.add_argument("--require-c-oracle", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)
    if args.self_test:
        return self_test()
    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"error: source root does not exist: {root}", file=sys.stderr)
        return 2
    report = run(root, args.require_c_oracle)
    if not args.quiet:
        print_report(report)
    if args.json_output:
        output = Path(args.json_output)
        if not output.is_absolute(): output = root / output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(asdict(report), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return 0 if report.passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
